allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory.set(file('../build'))
subprojects {
    layout.buildDirectory.set(
        rootProject.layout.buildDirectory.dir(project.name)
    )
}

subprojects { subproject ->
    subproject.tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:-options"
    }
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                if (namespace == null) {
                    def g = project.group?.toString()
                    if (g != null && !g.isEmpty()) {
                        namespace = g
                    }
                }
                compileSdkVersion 36
                buildToolsVersion "36.0.0"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
